// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWUuEV9Bq3mDOU8GAUFxXxcMWvGp-68s',
    appId: '1:18149423909:web:cc581e512ebd6c7758b8cc',
    messagingSenderId: '18149423909',
    projectId: 'flutter-push-notificatio-3a9b7',
    authDomain: 'flutter-push-notificatio-3a9b7.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-3a9b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVANVUI_ykRwi5MyzelwSxixr2Ftp10kA',
    appId: '1:18149423909:android:f0bc4d567e6b206958b8cc',
    messagingSenderId: '18149423909',
    projectId: 'flutter-push-notificatio-3a9b7',
    storageBucket: 'flutter-push-notificatio-3a9b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1jruUqBVXEGaC5gFJ-IbhyP5Z6K861c',
    appId: '1:18149423909:ios:eee1abe5c76a4d3e58b8cc',
    messagingSenderId: '18149423909',
    projectId: 'flutter-push-notificatio-3a9b7',
    storageBucket: 'flutter-push-notificatio-3a9b7.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotfications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1jruUqBVXEGaC5gFJ-IbhyP5Z6K861c',
    appId: '1:18149423909:ios:eee1abe5c76a4d3e58b8cc',
    messagingSenderId: '18149423909',
    projectId: 'flutter-push-notificatio-3a9b7',
    storageBucket: 'flutter-push-notificatio-3a9b7.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotfications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXWUuEV9Bq3mDOU8GAUFxXxcMWvGp-68s',
    appId: '1:18149423909:web:2e44bb2e678c8dc358b8cc',
    messagingSenderId: '18149423909',
    projectId: 'flutter-push-notificatio-3a9b7',
    authDomain: 'flutter-push-notificatio-3a9b7.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-3a9b7.firebasestorage.app',
  );
}
